### ISSUE TITLE
625588839

### ISSUE THREAD

**Issue by Teshidesu** [Teshidesu/Teshidesu#1]
![dacgjfr-4032b750-412e-47c1-8218-c09b8f958e77](https://github.com/Teshidesu/Teshidesu/assets/118557327/51cd7a58-5fc5-4385-a5ac-7cc0fcd02398)

**Comment by AngelDev72** [comment]
Looking at your GitHub, the only thing that I think has an issue is your LinkedIn badge. It doesn't link to your profile. All other is awesome.
