### ISSUE TITLE
deberias comer mas arroz

### ISSUE THREAD

**Issue by JeyffersonGomez** [Teshidesu/Teshidesu#2]
Wey literalme pense que eras chavo...

**Comment by Teshidesu** [comment]
OMG!!
leave me alone! 
deleted me from here

**Comment by JeyffersonGomez** [comment]
**QUE JESOO**

**Comment by Teshidesu** [comment]
STAAAAP
### NO MORE COMMITS HERE

**Comment by JeyffersonGomez** [comment]
### **STOP CON "A" 💀**
